"""The Alembic migrations must produce exactly the schema the models describe."""

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected


def test_migrations_match_models(tmp_path, monkeypatch):
    from app.core.config import get_settings

    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'migrate.db'}")
    get_settings.cache_clear()
    try:
        cfg = Config("alembic.ini")
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)  # raises if models and migrations differ
        except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
            raise AssertionError(f"Models changed without a migration: {exc}") from exc
        command.downgrade(cfg, "base")
    finally:
        get_settings.cache_clear()
